-- 创建分类表
create table categories (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 创建商品表
create table products (
  id bigint generated by default as identity primary key,
  name text not null,
  category_id bigint references categories(id),
  quantity integer default 0,
  price decimal(10,2),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 创建交易记录表（入库/出库）
create table transactions (
  id bigint generated by default as identity primary key,
  product_id bigint references products(id),
  type text check (type in ('IN', 'OUT')),
  quantity integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 开启 Row Level Security (RLS)
alter table categories enable row level security;
alter table products enable row level security;
alter table transactions enable row level security;

-- 创建简单的策略（允许所有读写，实际生产中需要更严格的控制）
create policy "Enable read access for all users" on categories for select using (true);
create policy "Enable insert access for all users" on categories for insert with check (true);

create policy "Enable read access for all users" on products for select using (true);
create policy "Enable insert access for all users" on products for insert with check (true);
create policy "Enable update access for all users" on products for update using (true);

create policy "Enable read access for all users" on transactions for select using (true);
create policy "Enable insert access for all users" on transactions for insert with check (true);
